# Encrypted storage connection string and passphrase
storage:
  connectionStringEncrypted: ""  # Encrypted Azure Storage connection string (base64)
  passphrase: ""                 # Passphrase to decrypt the connection string (or use environment variable)
  blobName: ""                   # Name of the Azure Blob container to access

# Local paths
paths:
  downloadPath: ""               # Folder where downloaded files will be saved